# Generated by Django 3.0.7 on 2020-06-19 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('published_at', models.CharField(max_length=100)),
                ('url_link', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=200)),
                ('source', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=150)),
            ],
        ),
    ]
