# Generated by Django 3.0.7 on 2020-06-19 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='author',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='description',
            field=models.CharField(max_length=700),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='image',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='published_at',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='source',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='title',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='url_link',
            field=models.CharField(max_length=300),
        ),
    ]
