# Generated by Django 3.0.7 on 2020-06-11 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0003_auto_20200604_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_money',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
