# Generated by Django 3.0.7 on 2020-06-12 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0005_remove_user_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='experience',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
