# Generated by Django 3.0.7 on 2020-06-05 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='image_floorplan',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
