# Generated by Django 3.0.7 on 2020-06-07 11:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('properties', '0004_property_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='watchers',
            field=models.ManyToManyField(related_name='watching', to=settings.AUTH_USER_MODEL),
        ),
    ]
