# Generated by Django 3.0.7 on 2020-06-09 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_property_watchers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='image_four',
            new_name='image_1',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='image_one',
            new_name='image_2',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='image_three',
            new_name='image_3',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='image_two',
            new_name='image_4',
        ),
    ]
