# Generated by Django 3.0.7 on 2020-06-09 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_auto_20200609_1219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='image_eight',
            new_name='image_5',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='image_five',
            new_name='image_6',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='image_nine',
            new_name='image_7',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='image_seven',
            new_name='image_8',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='image_six',
            new_name='image_9',
        ),
    ]
