# Generated by Django 3.0.7 on 2020-06-11 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_auto_20200609_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='database_ref',
            field=models.IntegerField(default='3'),
            preserve_default=False,
        ),
    ]
