# Generated by Django 3.0.7 on 2020-06-18 15:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('properties', '0009_auto_20200612_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='watchers',
            field=models.ManyToManyField(blank=True, null=True, related_name='watching', to=settings.AUTH_USER_MODEL),
        ),
    ]
