# Generated by Django 3.0.7 on 2020-06-23 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_auto_20200618_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='database_ref',
        ),
        migrations.AddField(
            model_name='property',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
