# Generated by Django 3.0.7 on 2020-06-05 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='property_id',
            new_name='property_detail',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='user_id',
            new_name='user',
        ),
    ]
